services:
  db:
    image: postgres:14.22
    restart: always
    shm_size: 128mb
    networks:
      - cesizen-dev
    environment:
      POSTGRES_PASSWORD: ${DB__Password}
      POSTGRES_USER: ${DB__Username}
      POSTGRES_DB: ${DB__Database}
    volumes:
      - cesizen-db-dev:/var/lib/postgresql/data/

  adminer:
    image: adminer:5.4.2
    restart: always
    networks:
      - cesizen-dev
    depends_on:
      - db
    ports:
      - 8082:8080

  smtp:
    image: maildev/maildev:2.2.1
    environment:
      MAILDEV_SMTP_PORT: ${Smtp__Port}
    networks:
      - cesizen-dev
    ports:
      - "8083:1080"

  cesizen-front-office-api:
    build:
      context: .
      dockerfile: src/Presentation/FrontOffice.Api/Dockerfile
    networks:
      - cesizen-dev
    ports:
      - 8080:80
    env_file:
      - .env
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "http://+:80"
    command: ["-i", "-d"]
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
    depends_on:
      - db

  cesizen-back-office:
    build:
      context: .
      dockerfile: src/Presentation/BackOffice/Dockerfile
    networks:
      - cesizen-dev
    env_file:
      - .env
    ports:
      - 8081:80
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "http://+:80"
      DetailedErrors: "true"
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
    depends_on:
      - db

networks:
  cesizen-dev:

volumes:
  cesizen-db-dev: