name: Tag release

on:
  pull_request:
    types: [closed]
    branches: [master]

jobs:
  create-tag:
    if: github.event.pull_request.merged == true && startsWith(github.head_ref, 'release/')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create and push tag
        run: |
          BRANCH_NAME="${{ github.head_ref }}"
          VERSION=v${BRANCH_NAME#release/}
          
          git tag "v${VERSION}"
          git push origin "v${VERSION}"